receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # jaeger_thrift:
  #   endpoint: "http://jaeger:14268/api/traces"
  logging:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:9464"
  azuremonitor:
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        instrumentation_key: "e0955eb4-1817-4a94-bf6e-d48f6ae54a8c"
        # maxbatchsize is the maximum number of items that can be
        # queued before calling to the configured endpoint
        maxbatchsize: 100
        # maxbatchinterval is the maximum time to wait before calling
        # the configured endpoint.
        maxbatchinterval: 10s

processors:
  batch:

extensions:
  health_check:
  pprof:
    #endpoint: 0.0.0.0:1888
  zpages:
    #endpoint: 0.0.0.0:55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, logging]
      # exporters: [zipkin, jaeger_thrift, logging]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]